services:
  - type: web
    name: house-price-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir housing_price_prediction app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
